sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy

install:
  # Build/test dependencies
  - python setup.py install

script:
  # TODO: linting
  # run the namebench test
  - python namebench.py

notifications:
  email: false
