sudo: false
language: python
python:
  - 2.6
  - 2.7
#  - 3.2
#  - 3.3
#  - 3.4
  - pypy

install:
  # Build/test dependencies
  - python setup.py install
  - pip install pylint

script:
  # TODO: linting
  - pylint --reports=y *.py
  # run the namebench test
  - python namebench.py

notifications:
  email: false
